import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const filename=process.argv[2];if(!filename)throw Error('Pass the current portfolio snapshot');
const original=JSON.parse(fs.readFileSync(filename,'utf8')).data;
const stub={addEventListener(){},querySelectorAll(){return []},style:{},classList:{toggle(){}}};
const ctx=vm.createContext({document:{querySelector:()=>stub,querySelectorAll:()=>[]},window:{addEventListener(){}},structuredClone,source:structuredClone(original)});
vm.runInContext(fs.readFileSync('src/app.js','utf8').replace(/init\(\);\s*$/,''),ctx);vm.runInContext('data=normalize(source)',ctx);
const home=vm.runInContext('home()',ctx);assert.equal((home.match(/class="overview-card/g)||[]).length,4);assert.equal((home.match(/class="image-frame/g)||[]).length,4);
const about=vm.runInContext('aboutPage()',ctx);const life=original.projects.find(p=>p.category==='life');assert.equal((about.match(/class="about-photo"/g)||[]).length,life.images.length);assert.ok(about.includes('Shenzhen, China'));assert.ok(about.includes('ee1Ee_1'));assert.ok(about.includes('People, still life & feeling.'));assert.ok(about.includes('人、静物、感受。'));assert.ok(about.includes('我们跟随着本能创作，看似是意外的产生，其实是我们命中注定的东西。'));assert.ok(!about.includes('Observations'));
const stillPage=vm.runInContext("workPage('still')",ctx);assert.ok(stillPage.includes('class="project-cover-index"'));assert.ok(stillPage.indexOf('data-index-target="p-d72aade5')<stillPage.indexOf('data-index-target="p-cf588cc9'));assert.equal((stillPage.match(/class="cover-index-link/g)||[]).length,original.projects.filter(p=>p.category==='still'&&p.section!=='archive').length);
const archive=vm.runInContext("workPage('archive')",ctx),archiveCount=original.projects.filter(p=>p.section==='archive').flatMap(p=>p.images.filter(i=>i.type!=='video')).length;assert.equal((archive.match(/data-archive=/g)||[]).length,archiveCount);
const motion=vm.runInContext("workPage('motion')",ctx),videoCount=original.projects.filter(p=>p.category==='motion').flatMap(p=>p.images.filter(i=>i.type==='video')).length;assert.equal((motion.match(/class="archive-tile archive-video"/g)||[]).length,videoCount);assert.ok(!motion.includes('Motion</span>'));
for(const p of original.projects){const route=p.category==='life'?'aboutPage()':p.section==='archive'?"workPage('archive')":`workPage(${JSON.stringify(p.category)})`;const html=vm.runInContext(route,ctx);if(p.category==='life'){for(const i of p.images)assert.ok(html.includes(`data-photo="${i.id}"`),`Personal image missing: ${i.id}`)}else if(p.section==='archive'){for(const i of p.images.filter(i=>i.type!=='video'))assert.ok(archive.includes(`data-archive="${archiveCount-archiveCount}"`)||archive.includes(i.src),`Archive image missing: ${i.id}`)}else if(p.category==='motion'){for(const i of p.images.filter(i=>i.type==='video'))assert.ok(html.includes(`data-film="${videoCount-1}"`)||html.includes(i.src),`Video missing: ${i.id}`)}else for(const i of p.images)assert.ok(html.includes(`data-photo="${i.id}"`),`Work image missing: ${i.id}`)}
console.log(`Content preserved: ${original.projects.length} projects / ${original.projects.reduce((n,p)=>n+p.images.length,0)} media; 4 overview images; ${life.images.length} About images; ${archiveCount} archive images; ${videoCount} films.`);

assert.ok(about.includes("mailto:757335402@qq.com"));assert.ok(!about.includes("<span>·</span>"));assert.ok(!archive.includes("archive-heading"));assert.ok(!archive.includes("work-heading"));const fashion=vm.runInContext("workPage(\'fashion\')",ctx);assert.ok(!fashion.includes("work-heading"));assert.ok(fashion.includes("时装"));
