import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const elements=new Map();const el=key=>{if(!elements.has(key))elements.set(key,{addEventListener(){},classList:{toggle(){}},setAttribute(){},removeAttribute(){},style:{},querySelectorAll(){return []},showModal(){this.open=true},close(){this.open=false}});return elements.get(key)};
const ctx=vm.createContext({console,document:{querySelector:el,querySelectorAll:()=>[]},window:{addEventListener(){}},matchMedia:()=>({matches:true}),setTimeout,clearTimeout,structuredClone,Image:class{set src(v){this.onload?.()}},requestAnimationFrame:fn=>fn(),location:{hash:'#overview'}});
const code=fs.readFileSync('src/app.js','utf8').replace(/init\(\);\s*$/,'');vm.runInContext(code,ctx);ctx.seed=JSON.parse(fs.readFileSync('src/seed.json','utf8'));
vm.runInContext('data=normalize(seed);canEdit=true;',ctx);
const indexScroll=vm.runInContext("(()=>{const rail={clientTop:0,scrollTop:0,getBoundingClientRect:()=>({top:10,bottom:110}),scrollBy(){throw Error('reduced motion should scroll immediately')}};const link={getBoundingClientRect:()=>({top:120,bottom:132})};keepActiveIndexVisible(link,rail);return rail.scrollTop})()",ctx);assert.equal(indexScroll,26);assert.ok(fs.readFileSync('src/app.js','utf8').includes("keepActiveIndexVisible(active,rail)"));assert.ok(fs.readFileSync('src/style.css','utf8').includes('.work-page .cover-index-link.active{z-index:2;transform:scale(1.06)'));
const legacy=vm.runInContext("normalize({name:'Test',nameEn:'HUOHAI ZHANG',projects:[{id:'old-archive',title:'過往案例',category:'portrait',section:'archive',images:[{id:'a',src:'/seed/0353.jpg',name:'a.jpg',alt:'',wide:false}]},{id:'old-motion',title:'Motion',category:'motion',section:'work',images:[{id:'v',src:'/media/00000000-0000-0000-0000-000000000001.mp4',type:'video',name:'v.mp4',alt:'',wide:true}]}],categoryCovers:{}})",ctx);assert.equal(legacy.projects[0].section,'work');assert.equal(legacy.projects[0].category,'archive');assert.equal(legacy.projects[1].category,'archive');assert.equal(legacy.nameEn,'HOVAI');ctx.legacy=legacy;const legacyArchive=vm.runInContext("(data=legacy,workPage('archive'))",ctx);assert.ok(legacyArchive.includes('data-archive=\"0\"'));assert.ok(legacyArchive.includes('archive-mosaic'));assert.ok(!legacyArchive.includes('project-cover-index'));assert.deepEqual(Object.keys(legacy.categoryMobileCovers),[]);assert.ok(legacyArchive.includes('More Work'));vm.runInContext('data=normalize(seed)',ctx);
assert.ok(fs.readFileSync('src/index.html','utf8').includes('id="mobileCoverSettings"'));
const videoCard=vm.runInContext("media({title:'Motion',images:[]},{id:'clip',src:'/media/clip.mp4',type:'video',poster:'/seed/2000.jpg'},0,'story')",ctx);assert.ok(videoCard.includes('muted loop playsinline'));assert.ok(videoCard.includes('poster="/seed/2000.jpg"'));
const stillPhotos=vm.runInContext("data.projects.find(p=>p.category==='still'&&p.images.filter(i=>i.type!=='video').length>1).images.filter(i=>i.type!=='video').map(i=>i.id)",ctx);ctx.stillIds=stillPhotos;vm.runInContext('data.categoryCovers.still=stillIds[0];data.categoryMobileCovers.still=stillIds[1]',ctx);assert.equal(vm.runInContext("selectedCategoryCover(data,'still','desktop').id",ctx),stillPhotos[0]);assert.equal(vm.runInContext("selectedCategoryCover(data,'still','mobile').id",ctx),stillPhotos[1]);
let html=vm.runInContext('home()',ctx);assert.ok(html.includes('class="home-immersive"'));assert.equal((html.match(/data-home-index/g)||[]).length,8);assert.ok(html.includes('home-feature-frame'));assert.ok(html.includes('home-mobile-controls'));assert.ok(html.includes('SELECT A DIRECTION'));assert.ok(html.includes('People &amp; Still Life'));assert.ok(html.includes('aria-label="People &amp; Still Life / 人与静物 — open category"'));assert.ok(html.includes('href="#work/still"'));assert.equal((html.match(/class="home-thumb-link/g)||[]).length,4);assert.equal((html.match(/class="home-mobile-item/g)||[]).length,4);assert.ok(!html.includes('href="#work/archive"'));assert.ok(html.includes('04 / 04'));assert.ok(html.includes('href="#work/portrait"'));assert.ok(html.includes('href="#work/fashion"'));assert.ok(!html.includes('project-rail'));assert.ok(!html.includes('Observations'));assert.ok(!html.includes('Motion'));assert.ok(html.includes('href="#about"'));assert.ok(html.includes('SHENZHEN, CHINA'));assert.ok(html.includes('HOVAI'));
const cropSync=vm.runInContext("(()=>{data.categoryCoverAssets.still='/media/cropped-desktop.jpg';data.categoryCoverMobileAssets.still='/media/cropped-mobile.jpg';const page=home();return {desktop:page.includes('data-feature-src=\"/media/cropped-desktop.jpg\"'),mobile:page.includes('data-feature-src=\"/media/cropped-mobile.jpg\"')}})()",ctx);assert.deepEqual(JSON.parse(JSON.stringify(cropSync)),{desktop:true,mobile:true});assert.ok(fs.readFileSync('src/app.js','utf8').includes('item.dataset.featureSrc||next.currentSrc||next.src'));assert.ok(fs.readFileSync('src/style.css','utf8').includes('.work-page .cover-index-link.active{z-index:2;transform:scale(1.06);outline:0'));
assert.equal(vm.runInContext("workCategoryFromHash('#work/fashion')",ctx),'fashion');assert.equal(vm.runInContext("workCategoryFromHash('#work')",ctx),'still');assert.equal(vm.runInContext("workCategoryFromHash('#motion')",ctx),'archive');assert.ok(fs.readFileSync('src/app.js','utf8').includes('document.startViewTransition(()=>route())'));assert.ok(fs.readFileSync('src/style.css','utf8').includes('::view-transition-new(work-category-content)'));
const adminSource=fs.readFileSync('src/app.js','utf8'),adminCss=fs.readFileSync('src/style.css','utf8');assert.ok(adminSource.includes("action=i.crop&&e.target.closest('.crop-selection')?'move':'draw'"));assert.ok(adminSource.includes('data-cover-rotate'));assert.ok(adminCss.includes('.crop-picker .crop-selection{pointer-events:auto'));assert.ok(adminCss.includes('.thumb-crop-selection{pointer-events:auto'));assert.ok(adminSource.includes('data-transfer-image'));assert.ok(adminSource.includes('function moveMediaToProject'));assert.ok(adminSource.includes('list.scrollTop=scrollTop'));assert.ok(adminSource.includes('focused?.focus?.({preventScroll:true})'));assert.ok(adminCss.includes('.media-transfer'));
const moveCheck=vm.runInContext("(()=>{draft=structuredClone(data);const a=draft.projects.find(p=>p.category==='still'&&p.images.length),b=draft.projects.find(p=>p.id!==a.id);b.category='fashion';const image=a.images[0],id=image.id;draft.categoryCovers.still=id;draft.categoryCoverAssets.still='/cropped.jpg';draft.categoryMobileCovers.still=id;draft.categoryCoverMobileAssets.still='/mobile.jpg';const ok=moveMediaToProject(a.id,id,b.id);return {ok,sourceHas:a.images.some(i=>i.id===id),targetHas:b.images.some(i=>i.id===id),sourceCover:draft.categoryCovers.still,mobileCover:draft.categoryMobileCovers.still,original: image===b.images.at(-1)}})()",ctx);assert.deepEqual(JSON.parse(JSON.stringify(moveCheck)),{ok:true,sourceHas:false,targetHas:true,original:true});vm.runInContext('data=normalize(seed);draft=structuredClone(data)',ctx);
for(const layout of ['story','spread','pairs','grid']){ctx.layout=layout;html=vm.runInContext('group({...data.projects[0],composition:layout},0)',ctx);assert.ok(html.includes('comp-'+layout));assert.equal((html.match(/data-photo=/g)||[]).length,ctx.seed.projects[0].images.length)}
html=vm.runInContext("archiveMarkup([{id:'archive-p',title:'Hidden project title',images:[...Array.from({length:6},(_,n)=>({id:'archive-'+n,src:'/seed/0353.jpg',name:'a.jpg',alt:'',wide:false})),{id:'clip',src:'/media/clip.mp4',type:'video',poster:'/media/poster.jpg'}]}],false)",ctx);assert.ok(html.includes('archive-mosaic'));assert.ok(html.includes('archive-video'));assert.ok(!html.includes('archive-moving'));assert.ok(html.includes('src="/media/clip.mp4"'));assert.ok(html.includes('muted loop playsinline autoplay'));assert.ok(!html.includes('Hidden project title'));assert.ok(!html.includes('Selected work'));assert.ok(html.includes('preload="metadata"'));assert.ok(!html.includes('archive-stage'));assert.equal((html.match(/data-archive=/g)||[]).length,6);assert.ok(html.indexOf('class="archive-video')<html.indexOf('data-archive="4"'));
vm.runInContext("data.categoryCovers.still=data.projects[1].images[1].id",ctx);assert.equal(vm.runInContext("selectedCategoryCover(data,'still').id",ctx),ctx.seed.projects[1].images[1].id);
html=vm.runInContext("filmsMarkup([{...data.projects[0],images:[{id:'film',src:'/media/test.mp4',type:'video'}]}])",ctx);assert.ok(html.includes('film-rail'));assert.ok(html.includes('playsinline'));assert.ok(!html.includes('autoplay'));
vm.runInContext("openLight([{src:'/a.jpg',title:'A'},{src:'/b.jpg',title:'B'},{src:'/c.jpg',title:'C'}],0)",ctx);assert.equal(el('#lightbox').open,true);assert.equal(typeof el('#lightImg').onclick,'function');el('#lightImg').onclick();assert.equal(vm.runInContext('li',ctx),1);await vm.runInContext('stepLight(1)',ctx);assert.equal(el('#lightImg').src,'/c.jpg');assert.equal(el('#nextLight').disabled,true);await vm.runInContext('closeLight()',ctx);assert.equal(el('#lightbox').open,false);
ctx.fetch=async()=>({ok:true,json:async()=>({etag:'new'})});vm.runInContext('draft=structuredClone(data);route=()=>{};',ctx);await el('#save').onclick();assert.equal(el('#projectEditor').inert,false);assert.equal(el('#save').disabled,false);
console.log('Passed: E-style immersive desktop and four-cover mobile carousel with More Work separate, editorial layouts, staggered mixed image/video archive, independent covers, lightbox navigation, editable state after save');

// Non-destructive crop settings affect presentation only, never image URLs.
html=vm.runInContext("frameImage({src:'/media/original.jpg',width:1600,height:2400,focusX:20,focusY:30},{ratio:1,fit:'cover'})",ctx);assert.ok(html.includes('--focus-x:20%'));assert.ok(html.includes('--focus-y:30%'));assert.ok(html.includes('--image-fit:cover'));assert.ok(html.includes('src="/media/original.jpg"'));
assert.equal(vm.runInContext("slotRatio({}, {src:'/x.jpg',width:1600,height:2400,frame:'original'},0,'spread')",ctx),2/3);
assert.equal(vm.runInContext("compositionOf({images:[{src:'/1',width:2000,height:1000},{src:'/2',width:2000,height:1000}]})",ctx),'pairs');
console.log('Passed: crop focus, original source preservation, explicit original frame, automatic composition');
const first=ctx.seed.projects[0],image=first.images[0];image.crop={x:20,y:10,w:40,h:60};const cropped=vm.runInContext('frameImage(seed.projects[0].images[0],{ratio:1})',ctx);assert.ok(cropped.includes('user-crop'));assert.ok(cropped.includes('--focus-x:33.333'));assert.ok(cropped.includes('--focus-y:25%'));const projectHtml=vm.runInContext('group(seed.projects[0],0)',ctx);assert.ok(!projectHtml.includes('project-heading'));assert.ok(!projectHtml.includes('project-number'));
// The carousel advances on desktop as well as mobile and exposes only the four selected destinations.
const navItems=['still','portrait','fashion','about'].map((key,n)=>({dataset:{key,en:key,cn:key,count:`0${n+1} / 04`},href:key==='about'?'#about':`#work/${key}`,attributes:{},setAttribute(name,value){this.attributes[name]=value},removeAttribute(name){delete this.attributes[name]},classList:{toggle(){}},addEventListener(){},closest(){return null},querySelector(){return {src:'/shared.jpg',currentSrc:'/shared.jpg'}}}));
const feature={dataset:{key:'still'},href:'#work/still',setAttribute(){},addEventListener(){},classList:{add(){},remove(){}}};
const textNode=()=>({textContent:''});const featureMedia={querySelector(q){return q==='.home-feature-incoming'?null:{src:'/shared.jpg'}},classList:{add(){},remove(){}}};const titleNode=textNode(),cnNode=textNode(),countNode=textNode(),mobileCountNode=textNode();
const switcher={querySelector(q){return ({'[data-feature-media]':featureMedia,'[data-feature-link]':feature,'[data-feature-title]':titleNode,'[data-feature-cn]':cnNode,'[data-feature-count]':countNode,'[data-carousel-count]':mobileCountNode,'.home-thumb-tray':{addEventListener(){}}})[q]},querySelectorAll(q){return q==='[data-home-index]'?navItems:q==='.home-mobile-item'?navItems:[]}};
ctx.root={querySelector:()=>switcher};ctx.setTimeout=(fn,ms)=>{ctx.carouselTick=fn;ctx.carouselDelay=ms;return 1};ctx.clearTimeout=()=>{};
vm.runInContext('pageObservers=[];bindHomeSwitcher(root)',ctx);assert.equal(typeof ctx.carouselTick,'function');assert.equal(ctx.carouselDelay,3000);ctx.carouselTick();assert.equal(feature.href,'#work/portrait');assert.equal(countNode.textContent,'02 / 04');assert.equal(navItems[1].attributes['aria-current'],'true');assert.equal(navItems[0].attributes['aria-current'],undefined);vm.runInContext('cleanPage()',ctx);
console.log('Passed: four desktop choices and automatic category advancement without a viewport-width gate');

assert.ok(vm.runInContext("Math.abs(1.5*coverFrameRect({src:'/x.jpg',width:1200,height:800},'desktop').w/coverFrameRect({src:'/x.jpg',width:1200,height:800},'desktop').h-coverFrameAspect('desktop'))<.01",ctx));assert.equal(vm.runInContext("Math.round(coverFrameRect({src:'/x.jpg',width:1200,height:800},'mobile').w)",ctx),53);assert.ok(vm.runInContext("coverFrameRect({src:'/x.jpg',width:1200,height:800},'desktop',.5).w<coverFrameRect({src:'/x.jpg',width:1200,height:800},'desktop').w",ctx));console.log('Passed: responsive cover ratios and adjustable frame size');
